config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :users
  resources :feeds
  resources :favorites, only: [:create, :destroy, :index]

  resources :feeds do
    collection do
    post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed
end

app/models/feed.rb
class Feed < ApplicationRecord
  validates :content, presence: true, length: {in: 1..140}
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{maximum: 30}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  validates :image, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  mount_uploader :image, ImageUploader
  has_many :feeds
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(feed_id: params[:feed_id])
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}'s post has been added to favorites"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to feeds_path, notice: "#{favorite.feed.user.name}'s post has been removed to favorites"
  end
  def index
    @favorites = current_user.favorites
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :user_login_check, only: [:new]

  def index
    @feeds = Feed.all
  end

  def show
    @favorite = current_user.favorites.find_by(feed_id: @feed.id)
  end

  def new
      @feed = current_user.feeds.build
   end

   def edit
       if @feed.user != current_user
         flash.now[:error] = 'unauthorized access!'
         redirect_to feeds_path
       else
     end
   end

   def create
   @feed= current_user.feeds.build(feed_params)
   if params[:back]
     render :new
   else
   if @feed.save
     FeedMailer.feed_mail(@feed).deliver
     redirect_to feeds_path, notice: 'Feed was posted'
   else
     render :new
   end
 end
end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new if @feed.invalid?
  end
  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was updated' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @feed.destroy
      redirect_to feeds_url, notice: 'Feed was deleted'
    end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = Feed.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def feed_params
    params.require(:feed).permit(:image, :content, :image_cache, :user_id)
  end

  def user_login_check
  unless logged_in?
    redirect_to root_path
   end
 end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
   end
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'Login failed'
      render :new
    end
   end
  def destroy
     session.delete(:user_id)
     flash[:notice] = 'Logged out'
     redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def show
       @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
      redirect_to user_path(@user.id)
      else
        render :new
      end
  end
  def  edit
   @user = User.find(params[:id])
 end

 def update
    @user = User.find(params[:id])
   if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "User was updated"

   else
   render :edit
   end
 end

 def  destroy
   @user.destroy
   redirect_to users_path, notice:"User was deleted!"
 end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>Favorites list</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Content</th>
    <th>Feed</th>
  </tr>
  <tr>
    <% @favorites.each do |favorite| %>
    <td><%= favorite.feed.user.name %></td>
    <td><%= favorite.feed.content %></td>
    <td><%= image_tag favorite.feed.image.url %></td>
  </tr>
<% end %>
</table>

  <%= link_to 'Back', feeds_path %>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true ,url: choose_new_or_edit) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>

  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/confirm.html.erb
<h1>Do you want to post this ?</h1>

<%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
  <!-- Description for displaying the uploaded image on the confirmation screen -->
  <%= form.hidden_field :content %>
  <p>Content: <%= @feed.content %></p>
  <%= image_tag feed.image.url, style:"width:200px;height:130px" if @feed.image && @feed.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Post" %>
  <% end %>
  <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "Do not post", name: 'Back' %>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'See', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds List</h1>
<br>
<table class="container">
  <div class="row">
    <% @feeds.each do |feed| %>
         <p><%= feed.user.name %></p>
         <p>Content: <%= feed.content %></p>
         <p><%= image_tag feed.image.url, style:"width:200px;height:130px" %></p>
         <tr>
           <button type="button" class="btn btn-info"><%= link_to 'See', feed, data: {confirm: 'Are you sure you want to see?'}%></button>
           <button type="button" class="btn btn-info"><%= link_to 'Edit', edit_feed_path(feed), data: {confirm: 'Are you sure you want to edit?'}%></button>
           <button type="button" class="btn btn-info"><%= link_to 'Delete', feed, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        </tr>
       <% end %>
       </div>
       </table>
 <br>

<button type="button" class="btn btn-info"><%= link_to 'New Feed', new_feed_path %></button>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @feed.content %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag feed.image.url, style:"width:200px;height:130px" %>
</p>

<% unless @feed.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Not a favorite', favorite_path(id: @favorite.id), method: :delete, class:'btn btn-danger' %>
  <% else %>
    <%= link_to 'Favorite', favorites_path(feed_id: @feed.id), method: :post, class:'btn btn-primary'%>
  <% end %>
  <% end %>
<% if logged_in? && @feed.user_id == current_user.id %>
  <button type="button" class="btn btn-success btn-sm"><%= link_to 'Edit', edit_feed_path(@feed) %></button>
  <button type="button" class="btn btn-danger btn-sm"><%= link_to 'Delete', @feed, method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

<button type="button" class="btn btn-dark btn-sm"><%= link_to 'Back', feeds_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>instagram-clone</title>
    <%= csrf_meta_tags %>
       <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<nav class="navbar navbar-expand-sm bg-danger navbar-dark">
<a class="navbar-brand" href="#">

<div class="style"><font size="14" color="black">instagram-clone</font></div></a>
<header>
    <div>
      <h1 class="Insta"></h1>
   </div>
  </header>
</nav>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id) %>
    <%= link_to "Log Out", session_path(current_user.id), method: :delete %>
    <% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Log In", new_session_path %>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h2><%= @user.errors.count%>From the error<%= @user.name if @user.name %><%= "User"  if @user.name.empty? %>Could not be registered.</h2>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
		<% end %>
		</ul>
	</div>
<% end %>

  <div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class =" users_h1_box "><h1> User's Edition Screen</h1></div>

  <%= form_with(model: @user, local: true ) do |f| %>
    <form class="login-container">
      <%= f.label "name：" %><br>
      <%= f.text_field :name %><br>
      <%= f.label "email：" %><br>
      <%= f.text_field :email %><br>
      <%= f.label "password："  %><br>
      <%= f.password_field :password %><br>
      <%= f.label "password_confirmation："%><br>
      <%= f.password_field :password_confirmation %><br><br>
      <%= f.label "profile picture"%>
      <% if @user.image.url  %>
        <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
      <% end %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %><br><br>

      <%= f.submit "Edit" %><br><br>
    </form>
    <% end %>
</div>
<%= link_to "Back", user_path(@user.id)%> 

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<br>
<table class="container">
  <thead>
    <tr class="row">
      <th class="col-md-4">Profile picture</th>
      <th class="col-md-4">Name</th>
      <th class="col-md-4">Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="row">
        <td class="col-md-4"><%= image_tag user.image.url %></td>
        <td class="col-md-4"><%= user.name %></td>
        <td class="col-md-4"><%= user.email %></td>
        <td><button type="button" class="btn btn-info btn-sm"><%= link_to 'See', user %></button></td>

      <% if current_user && current_user.id == user.id %>
        <td><button type="button" class="btn btn-success btn-sm"><%= link_to 'Edit', edit_user_path(user) %></button></td>
        <td><button type="button" class="btn btn-danger btn-sm"><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>

</table>
<br>
<button type="button" class="btn btn-info"><%= link_to 'New User', new_user_path %></button>

app/views/users/new.html.erb
<h1>Sign Up</h1>
 <% if @user.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>

 <%= form_with(model: @user, local: true) do |f| %>
 <%= f.label :image %>
 <%= f.file_field :image %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :email %>
 <%= f.email_field :email %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>
 <%= f.submit "Create my account" %>
 <% end %>

app/views/users/show.html.erb
<div class="users_h1_box"><h1><%= @user.name %>'s page</h1></div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile Picture:</strong>
  <%= image_tag feed.image.url, style:"width:200px;height:130px" %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if logged_in? %>
<%= link_to 'Favorites List',favorites_path, class:'btn btn-primary' %> |
<%= link_to "Edit", edit_user_path(current_user.id)%> |
<%= link_to 'Back', users_path %> |
<%= link_to 'New Feed', new_feed_path %>
<% end %>